version: 1
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: server.log
    when: midnight
    backupCount: 7
    encoding: utf8
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
    propagate: no
  uvicorn.error:
    handlers: [file, console]
    level: INFO
    propagate: no
  uvicorn.access:
    handlers: [file, console]
    level: INFO
    propagate: no
root:
  handlers: [file, console]
  level: INFO 